### PR TITLE
Adding Scala 2.12.14 to build and CI

### PR DESCRIPTION
**Pull request by TonioGela**
Tested locally and the tests are working flawlessly.
Hope for a release soon!

### CODE REVIEW

**Comment by cb372** [comment]
Thanks! I didn’t know about 2.12.14.

Could you update the list of versions in docs/README.md please.

**Comment by TonioGela** [comment]
> Thanks! I didn’t know about 2.12.14.

Well, it's scala stewart merit. One of my giter8 templates got updated, and scala-typed-hole was missing for scala 2.12.14 :)

> Could you update the list of versions in docs/README.md please.

Of course, I just did it. Thanks!

**Comment by TonioGela** [comment]
@cb372 the scala 2.12.14 version wasn't automatically published right?

**Comment by cb372** [comment]
Hmm, I pushed the v0.1.10 tag, which should have kicked off a release on Travis, but it looks like Travis missed the memo for some reason.

Sorry about that. I’ll check it tomorrow.

**Comment by TonioGela** [comment]
And If I have time I'll help you with #41, seems really like it's the moment :)

**Comment by TonioGela** [comment]
> Hmm, I pushed the v0.1.10 tag, which should have kicked off a release on Travis, but it looks like Travis missed the memo for some reason.
> 
> Sorry about that. I’ll check it tomorrow.

Hi Chris! I just notice [here](https://search.maven.org/search?q=g:com.github.cb372%20scala-typed-holes) that there's still no version for scala 2.12.14 :(

**Pull request merged**
