### PR TITLE
Add scala 2.12.9 and openjdk12

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Comment by cb372** [comment]
Thanks! Not sure why the build failed. Just rerunning it now.

**Comment by cb372** [comment]
WTF, it fails to compile on Scala 2.12.5 with Java 12? That seems unlikely.

https://travis-ci.org/cb372/scala-typed-holes/jobs/569953680

**Comment by regadas** [comment]
Hi @cb372 ! just noticed this! indeed there's something strange going lol. I can have a look later!

**Comment by cb372** [comment]
There is an easy solution to this: stop supporting Scala 2.12.0 to 2.12.5. I wouldn't mind doing that. If you're using a Scala version older than 2.12.6, you don't deserve nice things, and the number of versions this project is currently cross-built for is pretty ridiculous.

**Comment by regadas** [comment]
@cb372 I totally agreed with you! Went a bit further by just keeping 2 versions of 2.12. There's no reason not to use at least 2.12.8 these days really. (or 2.11.12 if you still in spark world 😄 )

**Comment by cb372** [comment]
Released as v0.0.10.

**Pull request merged**
