### PR TITLE
Cross-build for 2.13.6

### LINKED ISSUE #49: 2.13.6 support
As usual, the plugin needs to be cross-compiled to 2.13.6. I will make the change based on https://github.com/cb372/scala-typed-holes/commit/ef5f7003b0266deba01f2e8488d636605942cac2, just wanted to leave an issue so nobody duplicates the work.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #49.

### CODE REVIEW

**Comment by kubukoz** [comment]
@cb372 can you approve workflows?

**Comment by cb372** [comment]
Do I trust you enough? 👀 

OK, go on then.

**Comment by kubukoz** [comment]
Green!

**Comment by cb372** [comment]
Thanks! Released as v0.1.9

**Pull request merged**
