### PR TITLE
Compile against 2.13.0-RC2 

### PR DESCRIPTION
**Pull request by SimY4**

### CODE REVIEW

**Comment by cb372** [comment]
Thanks! Didn’t RC2 come out a couple of days ago? Maybe we should wait for a scalatest release and then target RC2 instead?

**Comment by SimY4** [comment]
@cb372 I checked and scalacheck is not yet available for 2.13.0-RC2. Need to wait for them first. It should happen soon, hopefully.

**Comment by cb372** [comment]
Thanks. I’ll try to make a release when I get home tonight.

**Comment by cb372** [comment]
Released 0.0.8.

**Pull request merged**
