### PR TITLE
Cross build for multiple Scala versions

### LINKED ISSUE #11: Packages for multiple patch versions of Scala
Version `0.0.4` is published for [`2.13.0-M5`, `2.12.8` and `2.11.12`](https://mvnrepository.com/artifact/com.github.cb372/scala-typed-holes).
Should it be just `2.12`, `2.11` (and `2.13.0-M5`)?

Is it really intentional that the package is published only for `2.12.8`, but not `2.12.7` for example?

### PR DESCRIPTION
**Pull request by sideeffffect**
fixes #11

### CODE REVIEW

**Comment by cb372** [comment]
Sorry, I don't really see the need for this. If somebody is using 2.12.x on their project, why would they not upgrade to 2.12.8 if they want to use the plugin?

Do you have a specific use-case, i.e. a project that uses 2.12.x but which you can't upgrade to 2.12.8? If so, I'd be interested to hear about it.

The downside of supporting all these different versions is that it slows down the release process. It also slows down `sbt +test`, which is quite a major part of my development workflow.

Whenever 2.12.9 comes out, I would expect to publish for 2.12.8 and 2.12.9 for a few releases.

**Comment by sideeffffect** [comment]
* apparently, publishing for many versions of Scala is something compiler plugins commonly do, so there are probably many use-cases, many of which I may not be aware of
* my particular use-case is ScalaZ ZIO
* are you sure it's really such a slow down on the release process? all the builds are parallel in Travis
* hmm, I see that having so many variants could be really pain in the neck if you need to run all the tests locally... would temporarily locally deleting some of those lines from .travis.yml help?
* would you be open to reconsidering your stance on this? I think it would make the usage of your plugin much more comfortable for *many* people -- I personally would like to use it as a globally enabled plugin for all projects I come accross without the need to fiddle with Scala versions

**Comment by cb372** [comment]
>are you sure it's really such a slow down on the release process? all the builds are parallel in Travis

Yes they are parallel in Travis, but the release process is done on my local machine. Every extra Scala version supported means one more Scala version for sbt to download, one more building of the jar, one more run of the tests, and six more artifacts to upload to Sonatype.

> I personally would like to use it as a globally enabled plugin

OK you have a point there. I was forgetting about this use case. I'm about to do a release anyway, so I'll merge this in and see how long the release takes. But I reserve the right to get rid of some of the older versions later if it gets too painful 😄

**Comment by sideeffffect** [comment]
@cb372 how about doing the release from Travis instead of your computer? there's [`sbt-ci-release`](https://github.com/olafurpg/sbt-ci-release) for that!
EDIT: https://github.com/cb372/scala-typed-holes/issues/16

**Pull request merged**
